import { format, subDays } from "date-fns"
import {
  Bell,
  Building2,
  CalendarDays,
  CircleDollarSign,
  ClipboardList,
  Container,
  CreditCard,
  Database,
  FileText,
  Gauge,
  Globe2,
  Settings,
  Shield,
  Ship,
  Truck,
  Users,
} from "lucide-react"

import { customers, moduleRoutes, ports, shippingLines } from "@/lib/elog/constants"
import type { DataRecord, ModuleConfig, ModuleKey } from "@/lib/elog/types"

const descriptions: Record<ModuleKey, string> = {
  dashboard: "Real-time command center across bookings, shipments, containers, appointments and finance.",
  bookings: "Create, review, approve and track customer logistics bookings.",
  shipments: "Plan milestones, carriers, exceptions and final delivery status.",
  containers: "Track container location, seal, temperature, status and movements.",
  appointments: "Calendar, slot utilization and gate operation control for trucks.",
  vehicles: "Vehicle registry with capacity, compliance expiry and assignment state.",
  drivers: "Driver profile, license, assignment, upcoming appointment and trip history.",
  documents: "Drag, preview, approve, replace, archive and delete operational documents.",
  invoices: "Invoice lifecycle, billing line items, taxes, balances and overdue monitoring.",
  payments: "Payment collection tracking across bank transfer, credit, online and cash methods.",
  customers: "Importer, exporter, shipper, consignee and forwarder account management.",
  partners: "Shipping line, depot, warehouse, broker and transport partner management.",
  reports: "Shipment, booking, container, revenue and customer performance reporting.",
  notifications: "Operational, billing and system notification center with preferences.",
  users: "Internal user lifecycle, organization membership, access state and roles.",
  roles: "Role catalog and permission matrix across eLog business capabilities.",
  "master-data": "Ports, terminals, gates, countries, container types, currencies and slots.",
  settings: "Organization profile, branding, notifications, integrations and security controls.",
}

function moduleShell(config: Omit<ModuleConfig, "route" | "description">): ModuleConfig {
  return { ...config, route: moduleRoutes[config.key], description: descriptions[config.key] }
}

function simpleModule(
  key: ModuleKey,
  title: string,
  icon: ModuleConfig["icon"],
  entityLabel: string,
  primaryAction: string,
  columns: Array<[string, string]>,
  statuses: string[]
): ModuleConfig {
  return moduleShell({
    key,
    title,
    entityLabel,
    icon,
    primaryAction,
    columns: columns.map(([fieldKey, label]) => ({ key: fieldKey, label })),
    filters: [{ key: "status", label: "Status", options: statuses }],
    records: Array.from({ length: key === "reports" ? 9 : 14 }, (_, index) => makeRecord(key, columns, statuses, index)),
    detailSections: [
      { title: "Overview", fields: columns.slice(0, 4).map(([fieldKey]) => fieldKey) },
      { title: "Operational Details", fields: columns.slice(4, 8).map(([fieldKey]) => fieldKey) },
      { title: "Activity History", fields: ["status", "updatedAt", "createdAt", "lastGenerated"] },
    ],
  })
}

export const modules: Record<ModuleKey, ModuleConfig> = {
  dashboard: moduleShell({
    key: "dashboard",
    title: "Dashboard",
    entityLabel: "Dashboard",
    icon: Gauge,
    columns: [],
    filters: [],
    records: [],
    detailSections: [],
  }),
  bookings: moduleShell({
    key: "bookings",
    title: "Booking Management",
    entityLabel: "Booking",
    icon: ClipboardList,
    primaryAction: "Create booking",
    columns: [
      ["bookingNumber", "Booking Number"],
      ["customer", "Customer"],
      ["bookingType", "Booking Type"],
      ["origin", "Origin"],
      ["destination", "Destination"],
      ["scheduledDate", "Scheduled Date"],
      ["status", "Status"],
      ["createdAt", "Created At"],
    ].map(([key, label]) => ({ key, label })),
    filters: [
      { key: "status", label: "Status", options: ["Draft", "Submitted", "Under Review", "Approved", "Rejected", "In Progress", "Completed", "Cancelled"] },
      { key: "bookingType", label: "Booking Type", options: ["FCL", "LCL", "Air", "Trucking", "Customs"] },
    ],
    records: Array.from({ length: 18 }, (_, index) => ({
      id: `booking-${index + 1}`,
      title: `BKG-2026-${String(123 + index).padStart(6, "0")}`,
      bookingNumber: `BKG-2026-${String(123 + index).padStart(6, "0")}`,
      customer: customers[index % customers.length],
      bookingType: ["FCL", "LCL", "Air", "Trucking", "Customs"][index % 5],
      origin: ports[index % ports.length],
      destination: ports[(index + 2) % ports.length],
      scheduledDate: format(subDays(new Date(2026, 6, 22), index - 6), "yyyy-MM-dd"),
      status: ["Draft", "Submitted", "Under Review", "Approved", "Rejected", "In Progress", "Completed", "Cancelled"][index % 8],
      createdAt: format(subDays(new Date(2026, 6, 20), index), "yyyy-MM-dd"),
      cargo: ["Furniture", "Frozen seafood", "Electronics", "Textiles"][index % 4],
      containers: `${1 + (index % 4)} x ${index % 2 ? "40HC" : "20GP"}`,
    })),
    detailSections: [
      { title: "Booking Summary", fields: ["bookingNumber", "status", "bookingType", "scheduledDate"] },
      { title: "Customer Information", fields: ["customer", "cargo", "containers"] },
      { title: "Route Information", fields: ["origin", "destination"] },
    ],
  }),
  shipments: moduleShell({
    key: "shipments",
    title: "Shipment Management",
    entityLabel: "Shipment",
    icon: Ship,
    primaryAction: "Create shipment",
    columns: [
      ["shipmentNumber", "Shipment Number"],
      ["bookingReference", "Booking Reference"],
      ["customer", "Customer"],
      ["shipmentMode", "Mode"],
      ["origin", "Origin"],
      ["destination", "Destination"],
      ["carrier", "Carrier"],
      ["etd", "ETD"],
      ["eta", "ETA"],
      ["status", "Current Status"],
      ["progress", "Progress"],
    ].map(([key, label]) => ({ key, label })),
    filters: [
      { key: "status", label: "Status", options: ["Planned", "Awaiting Pickup", "Picked Up", "At Origin Port", "Loaded", "In Transit", "At Destination Port", "Customs Clearance", "Out for Delivery", "Delivered", "Delayed", "Cancelled"] },
      { key: "shipmentMode", label: "Mode", options: ["Ocean", "Air", "Road", "Multimodal"] },
    ],
    records: Array.from({ length: 20 }, (_, index) => ({
      id: `shipment-${index + 1}`,
      title: `SHP-2026-${String(86 + index).padStart(6, "0")}`,
      shipmentNumber: `SHP-2026-${String(86 + index).padStart(6, "0")}`,
      bookingReference: `BKG-2026-${String(123 + index).padStart(6, "0")}`,
      customer: customers[(index + 1) % customers.length],
      shipmentMode: ["Ocean", "Air", "Road", "Multimodal"][index % 4],
      origin: ports[index % ports.length],
      destination: ports[(index + 3) % ports.length],
      carrier: shippingLines[index % shippingLines.length],
      vessel: ["Ever Given", "Maersk Hanoi", "ONE Integrity", "CMA CGM Mekong"][index % 4],
      voyageNumber: `VN${426 + index}`,
      etd: format(subDays(new Date(2026, 6, 23), index), "yyyy-MM-dd"),
      eta: format(subDays(new Date(2026, 7, 2), index), "yyyy-MM-dd"),
      status: ["Planned", "Awaiting Pickup", "Picked Up", "At Origin Port", "Loaded", "In Transit", "At Destination Port", "Customs Clearance", "Out for Delivery", "Delivered", "Delayed", "Cancelled"][index % 12],
      progress: `${Math.min(98, 12 + index * 5)}%`,
      assignedContainers: `${1 + (index % 5)} containers`,
    })),
    detailSections: [
      { title: "Overview", fields: ["shipmentNumber", "bookingReference", "status", "progress"] },
      { title: "Route", fields: ["origin", "destination", "carrier", "vessel", "voyageNumber"] },
      { title: "Cost Summary", fields: ["assignedContainers", "etd", "eta"] },
    ],
  }),
  containers: moduleShell({
    key: "containers",
    title: "Container Tracking",
    entityLabel: "Container",
    icon: Container,
    primaryAction: "Register container",
    columns: [
      ["containerNumber", "Container Number"],
      ["isoType", "ISO Type"],
      ["size", "Size"],
      ["shippingLine", "Shipping Line"],
      ["sealNumber", "Seal Number"],
      ["grossWeight", "Gross Weight"],
      ["currentLocation", "Current Location"],
      ["status", "Current Status"],
      ["shipmentReference", "Shipment Reference"],
      ["lastUpdated", "Last Updated"],
    ].map(([key, label]) => ({ key, label })),
    filters: [{ key: "status", label: "Status", options: ["Empty", "Booked", "Gate In", "In Yard", "Loaded", "In Transit", "Discharged", "Customs Hold", "Ready for Pickup", "Gate Out", "Returned"] }],
    records: Array.from({ length: 16 }, (_, index) => ({
      id: `container-${index + 1}`,
      title: `${["MSCU", "OOLU", "EGLV", "HLBU"][index % 4]}${1234567 + index}`,
      containerNumber: `${["MSCU", "OOLU", "EGLV", "HLBU"][index % 4]}${1234567 + index}`,
      isoType: index % 3 === 0 ? "45R1 Reefer" : index % 2 ? "42G1 Dry" : "22G1 Dry",
      size: index % 2 ? "40HC" : "20GP",
      shippingLine: shippingLines[index % shippingLines.length],
      sealNumber: `SEAL-${88210 + index}`,
      grossWeight: `${18 + index}.4 t`,
      currentLocation: ports[index % ports.length],
      status: ["Empty", "Booked", "Gate In", "In Yard", "Loaded", "In Transit", "Discharged", "Customs Hold", "Ready for Pickup", "Gate Out", "Returned"][index % 11],
      shipmentReference: `SHP-2026-${String(86 + index).padStart(6, "0")}`,
      lastUpdated: format(subDays(new Date(2026, 6, 22), index), "yyyy-MM-dd HH:mm"),
      temperature: index % 3 === 0 ? "-18 C" : "N/A",
    })),
    detailSections: [
      { title: "Container Overview", fields: ["containerNumber", "isoType", "size", "shippingLine", "grossWeight"] },
      { title: "Seal & Temperature", fields: ["sealNumber", "temperature", "currentLocation", "lastUpdated"] },
      { title: "Shipment Reference", fields: ["shipmentReference", "status"] },
    ],
  }),
  appointments: simpleModule("appointments", "Truck Appointment", CalendarDays, "Appointment", "Create appointment", [["appointmentNumber", "Appointment Number"], ["date", "Date"], ["timeSlot", "Time Slot"], ["truck", "Truck"], ["driver", "Driver"], ["containerNumber", "Container Number"], ["operationType", "Operation Type"], ["gate", "Gate"], ["status", "Status"]], ["Scheduled", "Confirmed", "Checked In", "At Gate", "In Progress", "Completed", "Delayed", "Cancelled", "No Show"]),
  vehicles: simpleModule("vehicles", "Vehicle Management", Truck, "Vehicle", "Add vehicle", [["plateNumber", "Plate Number"], ["vehicleType", "Vehicle Type"], ["transportCompany", "Transport Company"], ["capacity", "Capacity"], ["status", "Status"], ["registrationExpiry", "Registration Expiry"], ["insuranceExpiry", "Insurance Expiry"], ["assignedDriver", "Assigned Driver"]], ["Available", "Assigned", "In Transit", "Maintenance", "Inactive"]),
  drivers: simpleModule("drivers", "Driver Management", Users, "Driver", "Add driver", [["driverName", "Driver Name"], ["phone", "Phone"], ["licenseNumber", "License Number"], ["licenseType", "License Type"], ["licenseExpiry", "License Expiry"], ["company", "Company"], ["status", "Current Status"], ["assignedVehicle", "Assigned Vehicle"]], ["Available", "Assigned", "In Transit", "Inactive"]),
  documents: simpleModule("documents", "Document Center", FileText, "Document", "Upload document", [["documentName", "Document Name"], ["documentType", "Document Type"], ["referenceNumber", "Reference Number"], ["relatedEntity", "Related Entity"], ["uploadedBy", "Uploaded By"], ["uploadedAt", "Uploaded At"], ["expiryDate", "Expiry Date"], ["status", "Status"]], ["Draft", "Pending Review", "Approved", "Rejected", "Expired", "Archived"]),
  invoices: simpleModule("invoices", "Billing & Invoices", CircleDollarSign, "Invoice", "Create invoice", [["invoiceNumber", "Invoice Number"], ["customer", "Customer"], ["relatedBooking", "Related Booking"], ["invoiceDate", "Invoice Date"], ["dueDate", "Due Date"], ["subtotal", "Subtotal"], ["tax", "Tax"], ["total", "Total"], ["paidAmount", "Paid Amount"], ["balance", "Balance"], ["status", "Status"]], ["Draft", "Issued", "Partially Paid", "Paid", "Overdue", "Cancelled"]),
  payments: simpleModule("payments", "Payments", CreditCard, "Payment", "Record payment", [["paymentReference", "Payment Reference"], ["invoiceNumber", "Invoice Number"], ["customer", "Customer"], ["paymentMethod", "Payment Method"], ["paymentDate", "Payment Date"], ["amount", "Amount"], ["status", "Status"]], ["Pending Review", "Approved", "Rejected", "Paid"]),
  customers: simpleModule("customers", "Customer Management", Building2, "Customer", "Add customer", [["customerCode", "Customer Code"], ["companyName", "Company Name"], ["customerType", "Customer Type"], ["contactPerson", "Contact Person"], ["email", "Email"], ["phone", "Phone"], ["taxCode", "Tax Code"], ["status", "Status"]], ["Active", "Inactive", "Suspended"]),
  partners: simpleModule("partners", "Partner Management", Globe2, "Partner", "Add partner", [["partnerCode", "Partner Code"], ["companyName", "Company Name"], ["partnerType", "Partner Type"], ["contactPerson", "Contact Person"], ["email", "Email"], ["phone", "Phone"], ["status", "Status"]], ["Active", "Inactive", "Suspended"]),
  reports: simpleModule("reports", "Reports", Gauge, "Report", "Export report", [["reportName", "Report Name"], ["dateRange", "Date Range"], ["customer", "Customer"], ["status", "Status"], ["records", "Records"], ["lastGenerated", "Last Generated"]], ["Ready", "Draft", "Archived"]),
  notifications: simpleModule("notifications", "Notification Center", Bell, "Notification", "Mark all as read", [["title", "Title"], ["message", "Message"], ["type", "Type"], ["time", "Time"], ["status", "Read Status"], ["relatedEntity", "Related Entity"]], ["Unread", "Read"]),
  users: simpleModule("users", "User Management", Users, "User", "Invite user", [["name", "Name"], ["email", "Email"], ["organization", "Organization"], ["role", "Role"], ["status", "Status"], ["lastLogin", "Last Login"], ["createdAt", "Created At"]], ["Active", "Invited", "Suspended", "Inactive"]),
  roles: simpleModule("roles", "Role Management", Shield, "Role", "Create role", [["roleName", "Role Name"], ["description", "Description"], ["numberOfUsers", "Number of Users"], ["createdAt", "Created At"], ["updatedAt", "Updated At"]], ["Active", "Inactive"]),
  "master-data": simpleModule("master-data", "Master Data", Database, "Master Data", "Create master data", [["dataType", "Data Type"], ["code", "Code"], ["name", "Name"], ["description", "Description"], ["status", "Status"], ["updatedAt", "Updated At"]], ["Active", "Inactive"]),
  settings: simpleModule("settings", "System Settings", Settings, "Setting", "Save settings", [["settingGroup", "Setting Group"], ["settingName", "Setting Name"], ["value", "Value"], ["status", "Status"], ["updatedAt", "Updated At"]], ["Active", "Inactive"]),
}

export const dashboardData = {
  kpis: [
    { label: "Total Active Shipments", value: "486", delta: "+12.4%", comparison: "vs previous period", tone: "blue" as const },
    { label: "Pending Bookings", value: "74", delta: "-4.1%", comparison: "review queue", tone: "amber" as const },
    { label: "Containers In Transit", value: "1,284", delta: "+8.8%", comparison: "ocean and road", tone: "cyan" as const },
    { label: "Truck Appointments Today", value: "132", delta: "+6.2%", comparison: "42 slots open", tone: "green" as const },
    { label: "Outstanding Invoices", value: "$284K", delta: "+3.7%", comparison: "14 overdue", tone: "red" as const },
    { label: "On-time Delivery Rate", value: "94.6%", delta: "+1.9%", comparison: "last 30 days", tone: "green" as const },
  ],
  shipmentVolume: [
    { month: "Jan", shipments: 320, bookings: 280, revenue: 220 },
    { month: "Feb", shipments: 356, bookings: 302, revenue: 260 },
    { month: "Mar", shipments: 392, bookings: 344, revenue: 310 },
    { month: "Apr", shipments: 370, bookings: 338, revenue: 295 },
    { month: "May", shipments: 426, bookings: 390, revenue: 355 },
    { month: "Jun", shipments: 462, bookings: 414, revenue: 410 },
    { month: "Jul", shipments: 486, bookings: 448, revenue: 438 },
  ],
  distribution: [
    { name: "Approved", value: 38, color: "var(--success)" },
    { name: "Under Review", value: 22, color: "var(--warning)" },
    { name: "In Progress", value: 28, color: "var(--primary)" },
    { name: "Rejected", value: 12, color: "var(--destructive)" },
  ],
  activities: [
    { title: "BKG-2026-000137 created", description: "Lotus Retail submitted an FCL booking from Cat Lai Terminal.", time: "12 min ago" },
    { title: "SHP-2026-000091 delayed", description: "Carrier updated ETA by 18 hours at Singapore Port.", time: "34 min ago" },
    { title: "MSCU1234571 gate-in", description: "Container scanned at Cai Mep Terminal Gate 2.", time: "1h ago" },
    { title: "INV-2026-001248 paid", description: "Bank transfer matched automatically.", time: "2h ago" },
    { title: "APT-2026-000330 delayed", description: "Truck 51C-73009 checked in late.", time: "3h ago" },
  ],
  alerts: [
    ["Shipment delayed", "SHP-2026-000091 needs customer notification.", "High"],
    ["Container not gate-out", "EGLV1234574 has stayed in yard for 72 hours.", "Medium"],
    ["Document expiring", "Certificate of Origin expires in 48 hours.", "Medium"],
    ["Invoice overdue", "INV-2026-001251 is 9 days overdue.", "High"],
    ["Gate conflict", "Gate 3 has overlapping appointments at 10:00.", "High"],
  ],
}

function makeRecord(key: ModuleKey, columns: Array<[string, string]>, statuses: string[], index: number): DataRecord {
  const base: DataRecord = {
    id: `${key}-${index + 1}`,
    status: statuses[index % statuses.length],
    updatedAt: format(subDays(new Date(2026, 6, 22), index), "yyyy-MM-dd"),
    createdAt: format(subDays(new Date(2026, 6, 14), index), "yyyy-MM-dd"),
  }
  const values: Record<string, string | number> = {
    appointmentNumber: `APT-2026-${String(321 + index).padStart(6, "0")}`,
    date: format(subDays(new Date(2026, 6, 22), -index), "yyyy-MM-dd"),
    timeSlot: `${8 + (index % 9)}:00 - ${9 + (index % 9)}:00`,
    truck: `51C-${73000 + index}`,
    driver: ["Nguyen Van Minh", "Tran Quoc Bao", "Le Minh Anh", "Pham Gia Khang"][index % 4],
    containerNumber: `${["MSCU", "OOLU", "EGLV", "HLBU"][index % 4]}${1234567 + index}`,
    operationType: ["Container Pickup", "Container Drop-off", "Empty Return", "Cargo Delivery", "Cargo Collection"][index % 5],
    gate: `Gate ${1 + (index % 6)}`,
    plateNumber: `51C-${73000 + index}`,
    vehicleType: ["Prime mover", "Box truck", "Reefer truck", "Trailer"][index % 4],
    transportCompany: ["Saigon Trans", "Hai Phong Logistics", "Mekong Trucking"][index % 3],
    capacity: `${12 + index} t`,
    registrationExpiry: format(subDays(new Date(2027, 4, 12), index), "yyyy-MM-dd"),
    insuranceExpiry: format(subDays(new Date(2027, 8, 18), index), "yyyy-MM-dd"),
    assignedDriver: ["Nguyen Van Minh", "Tran Quoc Bao", "Le Minh Anh", "Unassigned"][index % 4],
    driverName: ["Nguyen Van Minh", "Tran Quoc Bao", "Le Minh Anh", "Pham Gia Khang"][index % 4],
    phone: `09${12000000 + index}`,
    licenseNumber: `VN-DL-${88000 + index}`,
    licenseType: ["FC", "C", "D", "E"][index % 4],
    licenseExpiry: format(subDays(new Date(2028, 3, 4), index), "yyyy-MM-dd"),
    company: ["Saigon Trans", "Mekong Trucking", "In-house Fleet"][index % 3],
    documentName: ["Bill of Lading", "Delivery Order", "Commercial Invoice", "Packing List"][index % 4],
    documentType: ["Bill of Lading", "Delivery Order", "Packing List", "Commercial Invoice", "Manifest", "Customs Declaration"][index % 6],
    referenceNumber: `DOC-REF-${7200 + index}`,
    relatedEntity: index % 2 ? `SHP-2026-${String(86 + index).padStart(6, "0")}` : `BKG-2026-${String(123 + index).padStart(6, "0")}`,
    uploadedBy: ["Linh Tran", "Bao Nguyen", "Admin User"][index % 3],
    uploadedAt: format(subDays(new Date(2026, 6, 21), index), "yyyy-MM-dd"),
    expiryDate: format(subDays(new Date(2026, 9, 12), index), "yyyy-MM-dd"),
    invoiceNumber: `INV-2026-${String(1245 + index).padStart(6, "0")}`,
    customer: customers[index % customers.length],
    relatedBooking: `BKG-2026-${String(123 + index).padStart(6, "0")}`,
    invoiceDate: format(subDays(new Date(2026, 6, 12), index), "yyyy-MM-dd"),
    dueDate: format(subDays(new Date(2026, 7, 12), index), "yyyy-MM-dd"),
    subtotal: `$${(2400 + index * 320).toLocaleString()}`,
    tax: `$${(240 + index * 32).toLocaleString()}`,
    total: `$${(2640 + index * 352).toLocaleString()}`,
    paidAmount: `$${(index % 3 === 0 ? 2640 + index * 352 : 900 + index * 80).toLocaleString()}`,
    balance: `$${(index % 3 === 0 ? 0 : 1740 + index * 272).toLocaleString()}`,
    paymentReference: `PAY-2026-${String(534 + index).padStart(6, "0")}`,
    paymentMethod: ["Bank Transfer", "Credit", "Online Payment", "Cash", "Other"][index % 5],
    paymentDate: format(subDays(new Date(2026, 6, 18), index), "yyyy-MM-dd"),
    amount: `$${(1200 + index * 210).toLocaleString()}`,
    customerCode: `CUS-${String(1000 + index).padStart(5, "0")}`,
    companyName: customers[index % customers.length],
    customerType: ["Importer", "Exporter", "Shipper", "Consignee", "Forwarder"][index % 5],
    partnerCode: `PTR-${String(2000 + index).padStart(5, "0")}`,
    partnerType: ["Shipping Line", "Transport Company", "Depot", "Warehouse", "Customs Broker", "Port Operator"][index % 6],
    contactPerson: ["Huyen Pham", "Long Nguyen", "Minh Dao"][index % 3],
    email: `contact${index + 1}@elog-demo.vn`,
    taxCode: `031${882100 + index}`,
    reportName: ["Shipment Summary", "Booking Performance", "Container Movement", "Truck Appointment", "Revenue Report", "Outstanding Invoice", "Customer Activity", "On-time Delivery", "Delayed Shipment"][index % 9],
    dateRange: "2026-07-01 - 2026-07-22",
    records: 120 + index * 17,
    lastGenerated: format(subDays(new Date(2026, 6, 22), index), "yyyy-MM-dd HH:mm"),
    title: ["Shipment delayed", "Invoice overdue", "Document expiring", "Gate slot conflict"][index % 4],
    message: ["SHP-2026-000091 is behind ETA by 18 hours", "INV-2026-001251 passed due date", "Delivery Order expires within 48 hours", "Two appointments selected Gate 3 at 10:00"][index % 4],
    type: ["Operational alerts", "Billing alerts", "System notifications"][index % 3],
    time: `${index + 1}h ago`,
    name: ["Linh Tran", "Bao Nguyen", "Mai Hoang", "Admin User"][index % 4],
    organization: ["eLog Vietnam", "North Branch", "South Branch"][index % 3],
    role: ["Operations Manager", "Finance", "Dispatcher", "Admin"][index % 4],
    lastLogin: format(subDays(new Date(2026, 6, 22), index), "yyyy-MM-dd HH:mm"),
    roleName: ["Admin", "Operations Manager", "Finance Controller", "Customer Service"][index % 4],
    description: "Role with scoped permissions for logistics workflows",
    numberOfUsers: 3 + index,
    dataType: ["Ports", "Terminals", "Gates", "Countries", "Cities", "Shipping Lines", "Container Types", "Cargo Types", "Vehicle Types", "Document Types", "Payment Methods", "Currencies", "Units", "Holidays", "Time Slots"][index % 15],
    code: `MD-${String(index + 1).padStart(4, "0")}`,
    settingGroup: ["General Settings", "Organization Profile", "Branding", "Notification Settings", "Booking Configuration", "Shipment Configuration", "Invoice Configuration", "Integration Settings", "Security Settings"][index % 9],
    settingName: ["REST API", "EDI", "Customs", "ERP", "Banking", "GPS", "Email", "SMS"][index % 8],
    value: index % 2 ? "Enabled" : "Configured",
  }
  columns.forEach(([fieldKey]) => {
    base[fieldKey] = values[fieldKey] ?? `${fieldKey}-${index + 1}`
  })
  base.title = String(base[columns[0][0]] ?? `${key}-${index + 1}`)
  return base
}
